// src/components/TiltedCard.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { useSpring } from "../composables/useSpring";
import "./TiltedCard.css";

const props = withDefaults(
  defineProps<{
    imageSrc: string;
    altText?: string;
    captionText?: string;
    containerHeight?: string;
    containerWidth?: string;
    imageHeight?: string;
    imageWidth?: string;
    scaleOnHover?: number;
    rotateAmplitude?: number;
    showMobileWarning?: boolean;
    showTooltip?: boolean;
    displayOverlayContent?: boolean;
    imageClassName?: string;
  }>(),
  {
    altText: "Tilted card image",
    captionText: "",
    containerHeight: "300px",
    containerWidth: "100%",
    imageHeight: "300px",
    imageWidth: "300px",
    scaleOnHover: 1.1,
    rotateAmplitude: 14,
    showMobileWarning: true,
    showTooltip: true,
    displayOverlayContent: false,
    imageClassName: "",
  },
);

const emit = defineEmits<{
  imageLoad: [event: Event];
}>();

const figureElement = ref<HTMLElement | null>(null);
const pointerX = ref(0);
const pointerY = ref(0);
const rotateXTarget = ref(0);
const rotateYTarget = ref(0);
const scaleTarget = ref(1);
const opacityTarget = ref(0);
const captionRotationTarget = ref(0);
let lastY = 0;

const cardSpring = { damping: 30, stiffness: 100, mass: 2 };
const rotateX = useSpring(rotateXTarget, cardSpring);
const rotateY = useSpring(rotateYTarget, cardSpring);
const scale = useSpring(scaleTarget, cardSpring);
const opacity = useSpring(opacityTarget, {
  damping: 20,
  stiffness: 100,
  mass: 1,
});
const captionRotation = useSpring(captionRotationTarget, {
  damping: 30,
  stiffness: 350,
  mass: 1,
});

const figureStyle = computed(() => ({
  height: props.containerHeight,
  width: props.containerWidth,
}));

const innerStyle = computed(() => ({
  width: props.imageWidth,
  height: props.imageHeight,
  transform: `rotateX(${rotateX.value}deg) rotateY(${rotateY.value}deg) scale(${scale.value})`,
}));

const imageStyle = computed(() => ({
  width: props.imageWidth,
  height: props.imageHeight,
}));

const captionStyle = computed(() => ({
  opacity: opacity.value,
  transform: `translate3d(${pointerX.value}px, ${pointerY.value}px, 0) rotate(${captionRotation.value}deg)`,
}));

const handleMouseMove = (event: MouseEvent) => {
  if (!figureElement.value) return;

  const rect = figureElement.value.getBoundingClientRect();
  const offsetX = event.clientX - rect.left - rect.width / 2;
  const offsetY = event.clientY - rect.top - rect.height / 2;

  rotateXTarget.value = (offsetY / (rect.height / 2)) * -props.rotateAmplitude;
  rotateYTarget.value = (offsetX / (rect.width / 2)) * props.rotateAmplitude;
  pointerX.value = event.clientX - rect.left;
  pointerY.value = event.clientY - rect.top;
  captionRotationTarget.value = -(offsetY - lastY) * 0.6;
  lastY = offsetY;
};

const handleMouseEnter = () => {
  scaleTarget.value = props.scaleOnHover;
  opacityTarget.value = 1;
};

const handleMouseLeave = () => {
  opacityTarget.value = 0;
  scaleTarget.value = 1;
  rotateXTarget.value = 0;
  rotateYTarget.value = 0;
  captionRotationTarget.value = 0;
};
</script>

<template>
  <figure
    ref="figureElement"
    class="tilted-card-figure"
    :style="figureStyle"
    @mousemove="handleMouseMove"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
  >
    <div v-if="showMobileWarning" class="tilted-card-mobile-alert">
      This effect is not optimized for mobile. Check on desktop.
    </div>

    <div class="tilted-card-inner" :style="innerStyle">
      <img
        :src="imageSrc"
        :alt="altText"
        :class="['tilted-card-img', imageClassName]"
        :style="imageStyle"
        draggable="false"
        @load="emit('imageLoad', $event)"
      />

      <div v-if="displayOverlayContent" class="tilted-card-overlay">
        <slot name="overlay" />
      </div>
    </div>

    <figcaption v-if="showTooltip" class="tilted-card-caption" :style="captionStyle">
      {{ captionText }}
    </figcaption>
  </figure>
</template>

// src/components/TiltedCard.tsx
import { useRef, useState } from "react";
import type { ReactNode, SyntheticEvent } from "react";
import { motion, useMotionValue, useSpring } from "motion/react";
import "./TiltedCard.css";

const springValues = {
  damping: 30,
  stiffness: 100,
  mass: 2,
};

interface TiltedCardProps {
  imageSrc: string;
  altText?: string;
  captionText?: string;
  containerHeight?: string;
  containerWidth?: string;
  imageHeight?: string;
  imageWidth?: string;
  scaleOnHover?: number;
  rotateAmplitude?: number;
  showMobileWarning?: boolean;
  showTooltip?: boolean;
  overlayContent?: ReactNode;
  displayOverlayContent?: boolean;
  imageClassName?: string;
  onImageLoad?: (event: SyntheticEvent<HTMLImageElement>) => void;
}

export default function TiltedCard({
  imageSrc,
  altText = "Tilted card image",
  captionText = "",
  containerHeight = "300px",
  containerWidth = "100%",
  imageHeight = "300px",
  imageWidth = "300px",
  scaleOnHover = 1.1,
  rotateAmplitude = 14,
  showMobileWarning = true,
  showTooltip = true,
  overlayContent = null,
  displayOverlayContent = false,
  imageClassName = "",
  onImageLoad,
}: TiltedCardProps) {
  const ref = useRef<HTMLElement | null>(null);

  const x = useMotionValue(0);
  const y = useMotionValue(0);
  const rotateXValue = useMotionValue(0);
  const rotateYValue = useMotionValue(0);
  const rotateX = useSpring(rotateXValue, springValues);
  const rotateY = useSpring(rotateYValue, springValues);
  const scaleValue = useMotionValue(1);
  const scale = useSpring(scaleValue, springValues);
  const opacityValue = useMotionValue(0);
  const opacity = useSpring(opacityValue);
  const rotateFigcaptionValue = useMotionValue(0);
  const rotateFigcaption = useSpring(rotateFigcaptionValue, {
    stiffness: 350,
    damping: 30,
    mass: 1,
  });

  const [lastY, setLastY] = useState(0);

  function handleMouse(event: React.MouseEvent<HTMLElement>) {
    if (!ref.current) return;

    const rect = ref.current.getBoundingClientRect();
    const offsetX = event.clientX - rect.left - rect.width / 2;
    const offsetY = event.clientY - rect.top - rect.height / 2;

    const rotationX = (offsetY / (rect.height / 2)) * -rotateAmplitude;
    const rotationY = (offsetX / (rect.width / 2)) * rotateAmplitude;

    rotateXValue.set(rotationX);
    rotateYValue.set(rotationY);

    x.set(event.clientX - rect.left);
    y.set(event.clientY - rect.top);

    const velocityY = offsetY - lastY;
    rotateFigcaptionValue.set(-velocityY * 0.6);
    setLastY(offsetY);
  }

  function handleMouseEnter() {
    scaleValue.set(scaleOnHover);
    opacityValue.set(1);
  }

  function handleMouseLeave() {
    opacityValue.set(0);
    scaleValue.set(1);
    rotateXValue.set(0);
    rotateYValue.set(0);
    rotateFigcaptionValue.set(0);
  }

  return (
    <figure
      ref={ref}
      className="tilted-card-figure"
      style={{
        height: containerHeight,
        width: containerWidth,
      }}
      onMouseMove={handleMouse}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
    >
      {showMobileWarning ? (
        <div className="tilted-card-mobile-alert">
          This effect is not optimized for mobile. Check on desktop.
        </div>
      ) : null}

      <motion.div
        className="tilted-card-inner"
        style={{
          width: imageWidth,
          height: imageHeight,
          rotateX,
          rotateY,
          scale,
        }}
      >
        <motion.img
          src={imageSrc}
          alt={altText}
          className={["tilted-card-img", imageClassName].filter(Boolean).join(" ")}
          style={{
            width: imageWidth,
            height: imageHeight,
          }}
          onLoad={onImageLoad}
          draggable={false}
        />

        {displayOverlayContent && overlayContent ? (
          <motion.div className="tilted-card-overlay">{overlayContent}</motion.div>
        ) : null}
      </motion.div>

      {showTooltip ? (
        <motion.figcaption
          className="tilted-card-caption"
          style={{
            x,
            y,
            opacity,
            rotate: rotateFigcaption,
          }}
        >
          {captionText}
        </motion.figcaption>
      ) : null}
    </figure>
  );
}
